const actionTypes = {
    NEW_MOVE:"NEW_MOVE",
    PLAYER_QUIT: "PLAYER_QUIT",
    CLEAR_CANDIDATE_MOVE:"CLEAR_CANDIDATE_MOVE",
    GENRATE_CANDIDATE_MOVE:"GENRATE_CANDIDATE_MOVE,",
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE',
}

  export default actionTypes;